# Generated by Django 6.0.4 on 2026-04-13 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_available', models.BooleanField(default=True, help_text='False when a client has booked this slot.', verbose_name='available')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='psychologists.psychologistprofile', verbose_name='psychologist')),
            ],
            options={
                'verbose_name': 'time slot',
                'verbose_name_plural': 'time slots',
                'db_table': 'time_slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('psychologist', 'date', 'start_time')},
            },
        ),
    ]
