# Generated by Django 6.0.4 on 2026-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True, help_text='False, если этот слот уже забронирован клиентом.', verbose_name='available'),
        ),
    ]
