# Generated by Django 6.0.4 on 2026-04-13 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier or CSS class.', max_length=100, null=True, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'specialization',
                'verbose_name_plural': 'specializations',
                'db_table': 'specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PsychologistSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary specialization')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_specializations', to='psychologists.psychologistprofile', verbose_name='psychologist')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_specializations', to='specializations.specialization', verbose_name='specialization')),
            ],
            options={
                'verbose_name': 'psychologist specialization',
                'verbose_name_plural': 'psychologist specializations',
                'db_table': 'psychologist_specializations',
                'unique_together': {('psychologist', 'specialization')},
            },
        ),
    ]
