# Generated by Django 6.0.4 on 2026-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='icon',
            field=models.CharField(blank=True, help_text='Необязательный идентификатор иконки или CSS-класс.', max_length=100, null=True, verbose_name='icon'),
        ),
    ]
