# Generated by Django 6.0.4 on 2026-04-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clients/avatars/', verbose_name='avatar')),
                ('is_profile_complete', models.BooleanField(default=False, help_text='Set to True once the client has filled in all required fields.', verbose_name='profile complete')),
            ],
            options={
                'verbose_name': 'client profile',
                'verbose_name_plural': 'client profiles',
                'db_table': 'client_profiles',
            },
        ),
    ]
