# Generated by Django 6.0.4 on 2026-04-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='last name')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='patronymic')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='psychologists/photos/', verbose_name='photo')),
                ('experience_years', models.IntegerField(blank=True, null=True, verbose_name='years of experience')),
                ('education', models.TextField(blank=True, null=True, verbose_name='education')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='session price')),
                ('diploma_scan', models.FileField(blank=True, upload_to='psychologists/diplomas/', verbose_name='diploma scan')),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True once an admin has verified the diploma.', verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('is_profile_complete', models.BooleanField(default=False, help_text='Set to True once the psychologist has filled in all required fields.', verbose_name='profile complete')),
            ],
            options={
                'verbose_name': 'psychologist profile',
                'verbose_name_plural': 'psychologist profiles',
                'db_table': 'psychologist_profiles',
            },
        ),
    ]
