# Generated by Django 6.0.4 on 2026-04-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychologists', '0001_initial'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='psychologists', through='specializations.PsychologistSpecialization', to='specializations.specialization'),
        ),
    ]
